# Generated by Django 3.2.13 on 2022-07-08 03:19

from django.db import migrations, models
import django_enum.fields
import django_enum.tests.app1.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnumTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_pos_int', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Value 1'), (2, 'Value 2'), (32767, 'Value 32767')], default=None, enum=django_enum.tests.app1.enums.SmallPosIntEnum, null=True)),
                ('small_int', django_enum.fields.EnumSmallIntegerField(choices=[(-32768, 'Value -32768'), (0, 'Value 0'), (1, 'Value 1'), (2, 'Value 2'), (32767, 'Value 32767')], default=32767, enum=django_enum.tests.app1.enums.SmallIntEnum)),
                ('pos_int', django_enum.fields.EnumPositiveIntegerField(choices=[(0, 'Value 0'), (1, 'Value 1'), (2, 'Value 2'), (2147483647, 'Value 2147483647')], default=2147483647, enum=django_enum.tests.app1.enums.PosIntEnum)),
                ('int', django_enum.fields.EnumIntegerField(choices=[(-2147483648, 'Value -2147483648'), (0, 'Value 0'), (1, 'Value 1'), (2, 'Value 2'), (2147483647, 'Value 2147483647')], enum=django_enum.tests.app1.enums.IntEnum, null=True)),
                ('big_pos_int', django_enum.fields.EnumPositiveBigIntegerField(choices=[(0, 'Value 0'), (1, 'Value 1'), (2, 'Value 2'), (2147483648, 'Value 2147483647')], default=None, enum=django_enum.tests.app1.enums.BigPosIntEnum, null=True)),
                ('big_int', django_enum.fields.EnumBigIntegerField(choices=[(-2147483649, 'Value -2147483649'), (1, 'Value 1'), (2, 'Value 2'), (2147483648, 'Value 2147483647')], default=-2147483649, enum=django_enum.tests.app1.enums.BigIntEnum)),
                ('constant', django_enum.fields.EnumFloatField(choices=[(3.141592653589793, 'Pi'), (2.71828, "Euler's Number"), (1.618033988749895, 'Golden Ratio')], default=None, enum=django_enum.tests.app1.enums.Constants, null=True)),
                ('text', django_enum.fields.EnumCharField(choices=[('V1', 'Value1'), ('V22', 'Value2'), ('V333', 'Value3'), ('D', 'Default')], default=None, enum=django_enum.tests.app1.enums.TextEnum, max_length=4, null=True)),
            ],
        ),
    ]
